# Python CircleCI 2.0 configuration file
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      environment:
          TZ: "Europe/Kiev"
    environment:
      TZ: "Europe/Kiev"
    working_directory: ~/PythonAQA

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: install allure
      - run:
          name: Install allure CLI
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo npm install -g allure-commandline --save-dev
      # Step 4: run linter and tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            flake8 --exclude=venv* --statistics  --max-line-length 180
            python3 -m pytest -v --reruns 3 --reruns-delay 1 --alluredir ~/PythonAQA/raw_test_results_json
      # Step 5: Generate HTML report
      - run:
          name: Generate report
          when: always
          command: |
            allure generate -c ~/PythonAQA/raw_test_results_json -o ~/PythonAQA/test-reports

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
          when: always
