# Python CircleCI 3.7 configuration file
version: 3.7
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    working_directory: ~/PythonAQA

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            flake8 --exclude=venv* --statistics  --max-line-length 180
            pytest -v --reruns 3 --reruns-delay 1 --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
